spring:
  cloud:
    azure:
      cosmos:
        key: Bh9yMoedWBsbnAgKA1gCoCmaRsjRQF68KkzWmcYzMqMiRYyNEB21Uv0Lmu9sjXav1ykDdEUtMvrbACDb4BMj8w==
        endpoint: https://mentalhealth-cosmosdb.documents.azure.com:443/
        database: mental-health